name: 1 version

concurrency: version

on:
  pull_request:
    branches: 
      - main
    types:
      - closed

jobs:

  version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      # this action is not triggering on push tags...
      # a push using the GITHUB_TOKEN can't trigger workflows.
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
          WITH_V: true

      - name: release notes
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }} 
          name: ${{ steps.tag.outputs.new_tag }}
          generateReleaseNotes: true

      - uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
  

  changed_files_check:
    runs-on: ubuntu-latest
    needs: version
    steps:

      - uses: actions/checkout@v4
        with: 
          fetch-depth: '0'

      - uses: tj-actions/changed-files@v41
        id: changed-requirements-file
        with:
          files: |
            requirements.txt

      - name: Has changed requirements
        if: ${{ steps.changed-requirements-file.outputs.any_changed == 'true' }}
        run: |
          for file in ${{ steps.changed-requirements-file.outputs.all_changed_files }}; do
            echo "$file"
          done
        