name: 2 on push tags
run-name:  ${{ github.ref_name }} 2 on push tags

on:
  push:
    tags:
      - 'v*'

env:
  ACTIONS_RUNNER_DEBUG: true  
            
jobs:

  example_tags:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref_name }}

      - uses: tj-actions/changed-files@v41
        id: changed-requirements-file
        with:
          files: |
            requirements.txt

      - name: Has changed requirements
        if: ${{ steps.changed-requirements-file.outputs.any_changed == 'true' }}
        run: |
          for file in ${{ steps.changed-requirements-file.outputs.all_changed_files }}; do
            echo "$file"
          done
