name: 3 on workflow run

on:
  workflow_run:
    workflows: [2 on push tags]
    types:
      - completed
    
env:
  ACTIONS_RUNNER_DEBUG: true  

jobs:

  example_triggered:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch}}

      - uses: tj-actions/changed-files@v41
        id: changed-requirements-file
        with:
          base_sha: ${{ github.event.workflow_run.head_sha }}
          files: |
            requirements.txt

      - name: Has changed requirements
        if: ${{ steps.changed-requirements-file.outputs.any_changed == 'true' }}
        run: |
          for file in ${{ steps.changed-requirements-file.outputs.all_changed_files }}; do
            echo "$file"
          done
