name: sandbox example
run-name: sandbox ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*'

jobs:

  example_tags:
    runs-on: ubuntu-latest

    steps:

      - name: echo stuff
        run: |
          echo ${{ github.event.sender.login }}

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Get requirements changed files
        uses: tj-actions/changed-files@v41
        id: changed-requirements-file
        with:
          files: |
            requirements.txt

      - name: Has changed requirements
        if: ${{ steps.changed-requirements-file.outputs.any_changed == 'true' }}
        run: |
          for file in ${{ steps.changed-requirements-file.outputs.all_changed_files }}; do
            echo "$file"
          done
